# DVC Pipeline Configuration
# Updated to match current src/data/ structure
# Tracks dependencies and outputs for all 8 steps

stages:
  step0_collect:
    cmd: python src/data/step0_data_collection.py
    deps:
      - src/data/step0_data_collection.py
    outs:
      - data/raw

  step1_clean:
    cmd: python src/data/step1_data_cleaning.py
    deps:
      - src/data/step1_data_cleaning.py
      - data/raw
    outs:
      - data/clean/fred_clean.csv
      - data/clean/market_clean.csv
      - data/clean/company_prices_clean.csv
      - data/clean/company_balance_clean.csv
      - data/clean/company_income_clean.csv
    metrics:
      - data/reports/step1_cleaning_report.csv:
          cache: false

  step2_features:
    cmd: python src/data/step2_feature_engineering.py
    deps:
      - src/data/step2_feature_engineering.py
      - data/clean
    outs:
      - data/features/fred_features.csv
      - data/features/market_features.csv
      - data/features/company_features.csv

  step3_merge:
    cmd: python src/data/step3_data_merging.py
    deps:
      - src/data/step3_data_merging.py
      - data/features/fred_features.csv
      - data/features/market_features.csv
      - data/features/company_features.csv
    outs:
      - data/features/macro_features.csv
      - data/features/merged_features.csv
    metrics:
      - data/reports/step3_merge_report.csv:
          cache: false

  step4_postmerge_clean:
    cmd: python src/data/step4_post_merge_cleaning.py
    deps:
      - src/data/step4_post_merge_cleaning.py
      - data/features/macro_features.csv
      - data/features/merged_features.csv
    outs:
      - data/features/macro_features_clean.csv
      - data/features/merged_features_clean.csv
    metrics:
      - data/reports/step4_postmerge_clean_report.csv:
          cache: false

  step5_bias:
    cmd: python src/data/step5_bias_detection_with_explicit_slicing.py
    deps:
      - src/data/step5_bias_detection_with_explicit_slicing.py
      - data/features/merged_features_clean.csv
    metrics:
      - data/bias_reports/bias_report_*.json:
          cache: false

  step6_anomaly:
    cmd: python src/data/step6_anomaly_detection.py
    deps:
      - src/data/step6_anomaly_detection.py
      - data/features/merged_features_clean.csv
    outs:
      - data/features/merged_features_clean_with_anomaly_flags.csv
    metrics:
      - data/anomaly_reports/anomaly_report_*.json:
          cache: false

  step7_drift:
    cmd: python src/data/step7_drift_detection.py
    deps:
      - src/data/step7_drift_detection.py
      - data/features/merged_features_clean.csv
    metrics:
      - data/drift_reports/drift_report_*.json:
          cache: false
